apiVersion: v1
kind: Service
metadata:
  name: news-cms
  namespace: mpj-cuongvc
  labels:
    app.kubernetes.io/name: news-cms
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: news-cms
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
